// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: scalar/chains/v1beta1/genesis.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { QueueState } from "../../utils/v1beta1/queuer";
import { Event } from "./events";
import { Params } from "./params";
import { ERC20TokenMetadata } from "./tokens";
import { CommandBatchMetadata, Gateway, SourceTx } from "./types";

export const protobufPackage = "scalar.chains.v1beta1";

export interface GenesisState {
  chains: GenesisState_Chain[];
}

export interface GenesisState_Chain {
  params?: Params | undefined;
  commandQueue?: QueueState | undefined;
  confirmedSourceTxs: SourceTx[];
  commandBatches: CommandBatchMetadata[];
  gateway?: Gateway | undefined;
  tokens: ERC20TokenMetadata[];
  events: Event[];
  confirmedEventQueue?: QueueState | undefined;
}

function createBaseGenesisState(): GenesisState {
  return { chains: [] };
}

export const GenesisState = {
  encode(
    message: GenesisState,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    for (const v of message.chains) {
      GenesisState_Chain.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GenesisState {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.chains.push(
            GenesisState_Chain.decode(reader, reader.uint32()),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      chains: globalThis.Array.isArray(object?.chains)
        ? object.chains.map((e: any) => GenesisState_Chain.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.chains?.length) {
      obj.chains = message.chains.map((e) => GenesisState_Chain.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(
    base?: I,
  ): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(
    object: I,
  ): GenesisState {
    const message = createBaseGenesisState();
    message.chains =
      object.chains?.map((e) => GenesisState_Chain.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGenesisState_Chain(): GenesisState_Chain {
  return {
    params: undefined,
    commandQueue: undefined,
    confirmedSourceTxs: [],
    commandBatches: [],
    gateway: undefined,
    tokens: [],
    events: [],
    confirmedEventQueue: undefined,
  };
}

export const GenesisState_Chain = {
  encode(
    message: GenesisState_Chain,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).ldelim();
    }
    if (message.commandQueue !== undefined) {
      QueueState.encode(
        message.commandQueue,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    for (const v of message.confirmedSourceTxs) {
      SourceTx.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    for (const v of message.commandBatches) {
      CommandBatchMetadata.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    if (message.gateway !== undefined) {
      Gateway.encode(message.gateway, writer.uint32(42).fork()).ldelim();
    }
    for (const v of message.tokens) {
      ERC20TokenMetadata.encode(v!, writer.uint32(50).fork()).ldelim();
    }
    for (const v of message.events) {
      Event.encode(v!, writer.uint32(58).fork()).ldelim();
    }
    if (message.confirmedEventQueue !== undefined) {
      QueueState.encode(
        message.confirmedEventQueue,
        writer.uint32(66).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GenesisState_Chain {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState_Chain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.commandQueue = QueueState.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.confirmedSourceTxs.push(
            SourceTx.decode(reader, reader.uint32()),
          );
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.commandBatches.push(
            CommandBatchMetadata.decode(reader, reader.uint32()),
          );
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.gateway = Gateway.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.tokens.push(
            ERC20TokenMetadata.decode(reader, reader.uint32()),
          );
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.events.push(Event.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.confirmedEventQueue = QueueState.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState_Chain {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      commandQueue: isSet(object.commandQueue)
        ? QueueState.fromJSON(object.commandQueue)
        : undefined,
      confirmedSourceTxs: globalThis.Array.isArray(object?.confirmedSourceTxs)
        ? object.confirmedSourceTxs.map((e: any) => SourceTx.fromJSON(e))
        : [],
      commandBatches: globalThis.Array.isArray(object?.commandBatches)
        ? object.commandBatches.map((e: any) =>
            CommandBatchMetadata.fromJSON(e),
          )
        : [],
      gateway: isSet(object.gateway)
        ? Gateway.fromJSON(object.gateway)
        : undefined,
      tokens: globalThis.Array.isArray(object?.tokens)
        ? object.tokens.map((e: any) => ERC20TokenMetadata.fromJSON(e))
        : [],
      events: globalThis.Array.isArray(object?.events)
        ? object.events.map((e: any) => Event.fromJSON(e))
        : [],
      confirmedEventQueue: isSet(object.confirmedEventQueue)
        ? QueueState.fromJSON(object.confirmedEventQueue)
        : undefined,
    };
  },

  toJSON(message: GenesisState_Chain): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.commandQueue !== undefined) {
      obj.commandQueue = QueueState.toJSON(message.commandQueue);
    }
    if (message.confirmedSourceTxs?.length) {
      obj.confirmedSourceTxs = message.confirmedSourceTxs.map((e) =>
        SourceTx.toJSON(e),
      );
    }
    if (message.commandBatches?.length) {
      obj.commandBatches = message.commandBatches.map((e) =>
        CommandBatchMetadata.toJSON(e),
      );
    }
    if (message.gateway !== undefined) {
      obj.gateway = Gateway.toJSON(message.gateway);
    }
    if (message.tokens?.length) {
      obj.tokens = message.tokens.map((e) => ERC20TokenMetadata.toJSON(e));
    }
    if (message.events?.length) {
      obj.events = message.events.map((e) => Event.toJSON(e));
    }
    if (message.confirmedEventQueue !== undefined) {
      obj.confirmedEventQueue = QueueState.toJSON(message.confirmedEventQueue);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState_Chain>, I>>(
    base?: I,
  ): GenesisState_Chain {
    return GenesisState_Chain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState_Chain>, I>>(
    object: I,
  ): GenesisState_Chain {
    const message = createBaseGenesisState_Chain();
    message.params =
      object.params !== undefined && object.params !== null
        ? Params.fromPartial(object.params)
        : undefined;
    message.commandQueue =
      object.commandQueue !== undefined && object.commandQueue !== null
        ? QueueState.fromPartial(object.commandQueue)
        : undefined;
    message.confirmedSourceTxs =
      object.confirmedSourceTxs?.map((e) => SourceTx.fromPartial(e)) || [];
    message.commandBatches =
      object.commandBatches?.map((e) => CommandBatchMetadata.fromPartial(e)) ||
      [];
    message.gateway =
      object.gateway !== undefined && object.gateway !== null
        ? Gateway.fromPartial(object.gateway)
        : undefined;
    message.tokens =
      object.tokens?.map((e) => ERC20TokenMetadata.fromPartial(e)) || [];
    message.events = object.events?.map((e) => Event.fromPartial(e)) || [];
    message.confirmedEventQueue =
      object.confirmedEventQueue !== undefined &&
      object.confirmedEventQueue !== null
        ? QueueState.fromPartial(object.confirmedEventQueue)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
    ? string | number | Long
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
