// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: scalar/covenant/v1beta1/params.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Threshold } from "../../utils/v1beta1/threshold";

export const protobufPackage = "scalar.covenant.v1beta1";

/** Params represent the genesis parameters for the module */
export interface Params {
  signingThreshold?: Threshold | undefined;
  signingTimeout: Long;
  signingGracePeriod: Long;
  activeEpochCount: Long;
  blockLimitPerSession: Long;
}

function createBaseParams(): Params {
  return {
    signingThreshold: undefined,
    signingTimeout: Long.ZERO,
    signingGracePeriod: Long.ZERO,
    activeEpochCount: Long.UZERO,
    blockLimitPerSession: Long.UZERO,
  };
}

export const Params = {
  encode(
    message: Params,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.signingThreshold !== undefined) {
      Threshold.encode(
        message.signingThreshold,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (!message.signingTimeout.equals(Long.ZERO)) {
      writer.uint32(16).int64(message.signingTimeout);
    }
    if (!message.signingGracePeriod.equals(Long.ZERO)) {
      writer.uint32(24).int64(message.signingGracePeriod);
    }
    if (!message.activeEpochCount.equals(Long.UZERO)) {
      writer.uint32(32).uint64(message.activeEpochCount);
    }
    if (!message.blockLimitPerSession.equals(Long.UZERO)) {
      writer.uint32(40).uint64(message.blockLimitPerSession);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Params {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.signingThreshold = Threshold.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.signingTimeout = reader.int64() as Long;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.signingGracePeriod = reader.int64() as Long;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.activeEpochCount = reader.uint64() as Long;
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.blockLimitPerSession = reader.uint64() as Long;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      signingThreshold: isSet(object.signingThreshold)
        ? Threshold.fromJSON(object.signingThreshold)
        : undefined,
      signingTimeout: isSet(object.signingTimeout)
        ? Long.fromValue(object.signingTimeout)
        : Long.ZERO,
      signingGracePeriod: isSet(object.signingGracePeriod)
        ? Long.fromValue(object.signingGracePeriod)
        : Long.ZERO,
      activeEpochCount: isSet(object.activeEpochCount)
        ? Long.fromValue(object.activeEpochCount)
        : Long.UZERO,
      blockLimitPerSession: isSet(object.blockLimitPerSession)
        ? Long.fromValue(object.blockLimitPerSession)
        : Long.UZERO,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.signingThreshold !== undefined) {
      obj.signingThreshold = Threshold.toJSON(message.signingThreshold);
    }
    if (!message.signingTimeout.equals(Long.ZERO)) {
      obj.signingTimeout = (message.signingTimeout || Long.ZERO).toString();
    }
    if (!message.signingGracePeriod.equals(Long.ZERO)) {
      obj.signingGracePeriod = (
        message.signingGracePeriod || Long.ZERO
      ).toString();
    }
    if (!message.activeEpochCount.equals(Long.UZERO)) {
      obj.activeEpochCount = (
        message.activeEpochCount || Long.UZERO
      ).toString();
    }
    if (!message.blockLimitPerSession.equals(Long.UZERO)) {
      obj.blockLimitPerSession = (
        message.blockLimitPerSession || Long.UZERO
      ).toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.signingThreshold =
      object.signingThreshold !== undefined && object.signingThreshold !== null
        ? Threshold.fromPartial(object.signingThreshold)
        : undefined;
    message.signingTimeout =
      object.signingTimeout !== undefined && object.signingTimeout !== null
        ? Long.fromValue(object.signingTimeout)
        : Long.ZERO;
    message.signingGracePeriod =
      object.signingGracePeriod !== undefined &&
      object.signingGracePeriod !== null
        ? Long.fromValue(object.signingGracePeriod)
        : Long.ZERO;
    message.activeEpochCount =
      object.activeEpochCount !== undefined && object.activeEpochCount !== null
        ? Long.fromValue(object.activeEpochCount)
        : Long.UZERO;
    message.blockLimitPerSession =
      object.blockLimitPerSession !== undefined &&
      object.blockLimitPerSession !== null
        ? Long.fromValue(object.blockLimitPerSession)
        : Long.UZERO;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
    ? string | number | Long
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
